# Étape 1 : pouvoir comparer l'adresse recherchée avec les données Gaïa.

## Filtres

<!-- - Définis dans les *settings* 🛠️.   -->
- Normaliser le texte pour la comparaison.  
- Pour les [**données du référentiel**]{.green2} ET pour les [**adresses recherchées**]{.blue2}.

## Filtres implémentés

- Lowercase  
- Asciifolding  
- Ponctuation  
- Séparation des nombres et lettres *(ex : 1er → 1 er)*  
- Suppression des "0" devant les nombres *(ex : 0033 → 33)*  
- [**Prise en compte des synonymes**]{.red2}  *(ex : ave = avenue, st = saint)*  

# Étape 2 : définir un score pour évaluer la pertinence.

## Base de données classique

*Exemple*  

| idVoie | nom de voie             |
|---|:-----------------------------|
| A | du general leclerc           |
| B | du general charles de gaulle |
| C | du point du jour             |
| D | verdier                      |
| E | des cours                    |

::: {.notes}
Nous allons faire un focus sur uniquement le "nom de voie" pour simplifier la compréhension de la théorie du moteur.  
:::

## Recherche par mot

[**Pour chaque nom de voie du référentiel**]{.blue2}, compter le nombre de mots qui sont retrouvés dans l'adresse recherchée : les **matchs** 🎯.  

*Exemple : score avec tokenizer "mot" de "45 avenue du general charles de gaulle"*

| idVoie | nom de voie             | score |
|---|:-----------------------------|-------|
| A | **du general** leclerc           | 2     |
| B | **du general charles de gaulle** | 5     |
| C | **du** point **du** jour         | 2     |
| D | verdier                          | 0     |
| E | des cours                        | 0     |

::: {.notes}
- Un match c'est chercher si une sous chaine du nom de voie, ici un mot, est incluse dans l'adresse recherchée.  
- Recherche par groupes de caractères également possible, abordée dans la suite.   
:::

## Score avec tokenizer "mot"

[**Tokenizer**]{.green2} = façon de découper le texte recherché et ciblé.  

<br>

[**Pour retourner la voie la plus pertinente**]{.blue2}, on construit un score pour chaque voie :
$$
score_{voie} = \sum_{\text{∀m} \in \text{M}} {nb\_occurrence}_m
$$

m = mot.  
M = ensemble des mots de l'adresse recherchée.  

[**Dans une grande base de données, c'est extrêmement long.**]{.red2}

::: {.notes}
Pour palier à ces temps de traitement qui explosent, on peut utiliser un nouvel outil qui permet de réorganiser nos bases de données : l'index inversé.  
:::

# Étape 3 : utiliser un index inversé. Mais qu'est ce donc ?

## Index inversé mot

*Exemple*  

<!-- | idVoie | nom de voie             |                        | mot     | occurrences              |
|---|:-----------------------------|                        |-----------|--------------------------|
| A | du general leclerc           |                        | general   | {"A": 1, "B": 1}         |
| B | du general charles de gaulle |        devient         | jour      | {"C": 1}                 |
| C | du point du jour             |                        | du        | {"A": 1, "B": 1, "C": 2} |
| D | verdier                      |                        | ...       | ...                      |
| E | des cours                    | -->

<div style="display: flex; justify-content: space-between;">

<table>
  <thead>
    <tr>
      <th>idVoie</th>
      <th>nom de voie</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>A</td>
      <td>du general leclerc</td>
    </tr>
    <tr>
      <td>B</td>
      <td>du general charles de gaulle</td>
    </tr>
    <tr>
      <td>C</td>
      <td>du point du jour</td>
    </tr>
    <tr>
      <td>D</td>
      <td>verdier</td>
    </tr>
    <tr>
      <td>E</td>
      <td>des cours</td>
    </tr>
  </tbody>
</table>

<!-- Ajoutez un espacement entre les deux tableaux -->
<div style="margin-left: 130px;"></div>

<table>
  <thead>
    <tr>
      <th>mot</th>
      <th>occurrences</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>general</td>
      <td>{"A": 1, "B": 1}</td>
    </tr>
    <tr>
      <td>jour</td>
      <td>{"C": 1}</td>
    </tr>
    <tr>
      <td>du</td>
      <td>{"A": 1, "B": 1, "C": 2}</td>
    </tr>
    <tr>
      <td>cours</td>
      <td>{"E": 1}</td>
    </tr>
    <tr>
      <td>...</td>
      <td>...</td>
    </tr>
  </tbody>
</table>
</div>

[**Comptage direct ⚡ des occurrences**]{.green2} de chaque mot de la base par idVoie.

::: {.notes}
- Faire un index inversé par mot, c'est récupérer tous les mots des noms de voie dans le référentiel et on les aplati dans une colonne.  
- Il y a autant de lignes qu'il y a de mots différents dans les noms de voie du référentiel. Les mots les plus fréquents seront ceux qui ont le plus d'occurences.  
- Nous obtenons directement le comptage de chaque mot par idVoie.  
- L'index inversé est fait en amont des recherches.  
::: 

# Étape 4 : prendre en compte les variations textuelles.

## Fuzziness

[**Contourner les petites fautes d'orthographes**]{.blue2} : [**fuzziness**]{.green2}.  

Pour matcher 🎯 deux mots avec une fuzziness de niveau 1 = corriger l'un des mots :  

- Ajout d'une lettre. *Ex: "verdiier"*  
- Suppression d'une lettre. *Ex: "verdie"*  
- Remplacement d'une lettre. *Ex: "verfier"*  
- Échanger deux lettres de place. *Ex: "evrdier"*  

Il est possible de comparer deux textes, deux n-grams ou n'importe quel autre groupe de caractères.  

::: {.notes}
La fuzziness n'est pas un tokenizer, une facon de decouper, c'est plutot une option qu'on rajoute pour matcher des sous chaine, peu importe le decoupage.
:::

## Une autre façon de découper : les n-grams

[**Prendre en compte les correspondances partielles**]{.blue2} : chaque mot est découpé en sous-chaînes de n caractères consécutifs.  

<br>

*Exemple de découpage en 3-grams de caractères du texte "avenue verdier" :*  
**ave, ven, enu, nue, ver, erd, rdi, die, ier**  

<br>

Si un mot est inférieur à la taille n, il n'aura pas de découpage en n-grams → pas présent dans l'index inversé n-gram.  


## Index inversé 3-grams

*Exemple*  

<!-- | 3-grams | occurrences           |
|---------|-----------------------|
| gen     | {"A": 1, "B": 1}      |
| cha     | {"B": 1}              |
| our     | {"C": 1, "E": 1}      |
| ...     | ...                   | -->



<div style="display: flex; justify-content: space-between;">

<table>
  <thead>
    <tr>
      <th>idVoie</th>
      <th>nom de voie</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>A</td>
      <td>du general leclerc</td>
    </tr>
    <tr>
      <td>B</td>
      <td>du general charles de gaulle</td>
    </tr>
    <tr>
      <td>C</td>
      <td>du point du jour</td>
    </tr>
    <tr>
      <td>D</td>
      <td>verdier</td>
    </tr>
    <tr>
      <td>E</td>
      <td>des cours</td>
    </tr>
  </tbody>
</table>

<!-- Ajoutez un espacement entre les deux tableaux -->
<div style="margin-left: 40px;"></div>

<table>
  <thead>
    <tr>
      <th>3-gram</th>
      <th>occurrences</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>gen</td>
      <td>{"A": 1, "B": 1}</td>
    </tr>
    <tr>
      <td>cha</td>
      <td>{"B": 1}</td>
    </tr>
    <tr>
      <td>our</td>
      <td>{"C": 1, "E": 1}</td>
    </tr>
    <tr>
      <td>oin</td>
      <td>{"C": 1}</td>
    </tr>
    <tr>
      <td>...</td>
      <td>...</td>
    </tr>
  </tbody>
</table>
</div>

::: {.notes}
- Il y a autant de lignes qu'il ya de trigrams différents dans les noms de voie du référentiel.  
- Si un mot est inférieur à la taille n=3, il ne sera pas pris en compte. Par exemple : du général de gaules, "du" et "de" n’apparaîtront pas dans l'index et donc ne seront pas pris en compte dans les matchs trigrams.  
:::

## Score avec tokenizer "n-grams"

Score pour chaque voie :
$$
score_{voie} = \sum_{\text{∀ngram} \in \text{N}} {nb\_occurrence}_{ngram}
$$

N = ensemble des n-grams de l'adresse recherchée.  

## Limites des n-grams

$$
\downarrow \text{taille n-grams}
\Rightarrow \text{taille index inversé} \uparrow 
\Rightarrow \text{temps de recherche} \uparrow
$$

- Limitation à n∈{3,4,5} pour notre cas.  
- Tests effectués pour choisir ces valeurs, en fonction de [**la précision et la rapidité**]{.green2} des requêtes.  

::: {.notes}
Donc avec tous ces éléments, on peut commencer à construire un score de plus en plus efficient pour trouver la voie la plus pertiente.
:::

## Score global 

Le score global va donc combiner la somme des matchs 🎯 au niveau :

- mot avec fuzziness.  
- n-grams.  

<br>

Il est possible de donner plus ou moins d'importance à ces différents niveaux de matchs 🎯.  

::: {.notes}
- On va chercher le nom de voie tel quel, sans découpage, au sein de l'adresse recherchée.  

- C'est pourquoi on va introduire la notion de boost.  
:::

<!-- ## Configurer le moteur ⚙️

Une fois qu'on a la théorie, il faut l'appliquer en pratique.  

Le package elasticsearch permet d'indexer les données en fournissant :  

- Un dataframe 📋 des données du référentiel Gaïa.  
- Des [**settings**]{.blue2} 🛠️ où on définit nos différents **analyzers**, englobant les filtres et le motizer.  
- Des [**mappings**]{.green2} 🏷️ où pour chaque **variable**, on fournit un analyzer.   -->

## Boost 🚀

- Chaque occurrence est multipliée par un facteur, appelé [**boost**]{.blue2} 🚀, qui dépend du niveau de match 🎯.  
- Personnalisation des **boosts** 🚀 pour être adapté aux données recherchées.  

::: {.notes}
Avec tous ces outils la, on peut faire une recherche !
:::

## Faire des recherches 🔍

*Requête 🔍 pour retrouver la voie :* 

À chaque match 🎯, le score va ⇡ en fonction du boost 🚀 associé.

| Variable | Tokenizer | Fuzzi 1 | Boost 🚀 |
|----------|-----------|---------|-----------|
| Nom de voie | Mot | ✅ | 15 |
| Type de voie | Mot | ✅ | 5 |
| Nom de voie | 3 à 5-grams | ❌ | 1 |

*Ex boost 200 : "3 rue du genral de gaulle" ⊃ "du gen[**e**]{.red2}ral de gaulle"*

::: {.notes}
- Requete gaia pour retrouver la voie.  
- Ici, on introduit le type de voie qui n'a pas été vu précédement, pour ne pas compliquer la compréhension de la théorie du moteur, mais la logique reste la meme que pour le nom de voie.  
- Attention,  pas de fuzzi sur les ngrams car on juge que les sous chaines sont déjà assez petites, c'est contre productif pour la rapidité et la précision des recherches d'ajouter de la fuzzi.  
- Il faut noter qu'on match à chaque sous-chaine, par exemple à chaque 3-grams de verdier dans 88 avenue verdier.  
- Les ngrams c'est notre dernier recours, on va retourner comme voie plus pertinente les match sur nom de voie complet et sur token mais ngrams c'est notre roue de secours.  
:::

## Retour sur le score global

$$
score_{voie} = \sum_{\text{∀n} \in \text{N}} \sum_{\text{∀t} \in \text{n}} boost_{n}*{nb\_occurrence}_{t}
$$

N = ensemble des niveaux *(niveau chaîne complète fuzzi, niveau mot fuzzi...)*.  
n = niveau.  
t = token, sous-chaîne *(un mot, un 3-grams...)*.  

::: {.notes}
- Formule mathématique du score pour retrouver la voie la plus pertiente dans Gaïa.  
:::