---
format:
  html:
    header-includes: |
        <link rel="icon" type="image/png" sizes="32x32" href="../_extensions/InseeFrLab/onyxia/favicon-32x32.png">
---
# Tests en Java

Actuellement, les étapes de recherche *adresse stricte* et de recherche *voie puis adresse* sont testées. Deux fichiers CSV, disponibles [ici](https://gitlab.insee.fr/geographie/gaia/gaia-parent/-/tree/main/gaia-core/src/test/resources/donnees?ref_type=heads), simulent les voies et les adresses Gaïa, constituant ainsi le référentiel de test. Ces fichiers servent à créer les indices de test pour les *adresses* et les *voies*.  

Les codes Java permettant de tester ces étapes sont accessibles aux liens suivants :  
- Pour la recherche [*adresse stricte*](https://gitlab.insee.fr/geographie/gaia/gaia-parent/-/blob/main/gaia-core/src/test/java/fr/insee/gaia/core/fonction/identification/service/IdentificationAdresseCompleteITest.java?ref_type=heads).  
- Pour la recherche [*voie puis adresse*](https://gitlab.insee.fr/geographie/gaia/gaia-parent/-/blob/main/gaia-core/src/test/java/fr/insee/gaia/core/fonction/identification/service/IdentificationAdresseClientITest.java?ref_type=heads).  


## Test recherche adresse stricte

Pour constituer ce test, l'objectif est de récupérer des adresses issues du référentiel de test et de vérifier leur identification. Les adresses à identifier doivent correspondre strictement à celles du référentiel, tant au niveau de l'orthographe que de la structure. Cependant, cette recherche dite *stricte* applique des filtres tels que la conversion en minuscules, la suppression des accents (asciifolding) et des signes de ponctuation. Par conséquent, nous testerons également l'identification d'adresses contenant ce type de caractères, en s'attendant à ce qu'elles soient correctement retrouvées.

Le test inclura également des adresses présentant des variations orthographiques. Dans ce cas, l'attente sera qu'elles **ne soient pas** identifiées dans le cadre de cette recherche stricte.


## Test recherche voie puis adresse

L'objectif ici est d'identifier, dans notre référentiel, des adresses comportant des variations orthographiques, des synonymes ou des erreurs. Pour garantir la robustesse des tests, il est nécessaire d'inclure des adresses correspondant à différents niveaux de qualité, tels que :  
- des adresses sûres dans des voies sûres,  
- des adresses douteuses dans des voies sûres,  
- des adresses situées dans des voies douteuses, etc.  
