---
title: "Identification d'adresses avec ElasticSearch"
subtitle: |
  **[Raya Berova & Benoît Hurpeau (DMRG)]{.blue2}**
date: "11/28/2024"
date-format: "D MMMM YYYY"
slide-number: true
# uncomment for French presentations:
lang: fr-FR
# for blind readers:
slide-tone: false
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
# uncomment to use the multiplex mode:
# multiplex: true
format:
  onyxia-revealjs:
    output-file: index.html
controls: true
css: ../custom.css
ascii: true
---


# Plan de la présentation

1️⃣ Contexte

2️⃣ Utilisation du référentiel Gaïa

3️⃣ Moteur de recherche ElasticSearch

4️⃣ Algorithme d'identification d'adresses

5️⃣ Performances de l'algorithme d'identification

6️⃣ Discussion


# 1️⃣ Introduction

{{< include sections/1-introduction.qmd >}}

# Plan de la présentation

1️⃣ Contexte

**2️⃣ Utilisation du référentiel Gaïa**

3️⃣ Moteur de recherche ElasticSearch

4️⃣ Algorithme d'identification d'adresses

5️⃣ Performances de l'algorithme d'identification

6️⃣ Discussion

# 2️⃣ Utilisation du référentiel Gaïa

{{< include sections/2-data.qmd >}}

# Plan de la présentation

1️⃣ Contexte

2️⃣ Utilisation du référentiel Gaïa

**3️⃣ Moteur de recherche ElasticSearch**

4️⃣ Algorithme d'identification d'adresses

5️⃣ Performances de l'algorithme d'identification

6️⃣ Discussion

# 3️⃣ Moteur de recherche ElasticSearch

{{< include sections/3-theory-elastic.qmd >}}

# Plan de la présentation

1️⃣ Contexte

2️⃣ Utilisation du référentiel Gaïa

3️⃣ Moteur de recherche ElasticSearch

**4️⃣ Algorithme d'identification d'adresses**

5️⃣ Performances de l'algorithme d'identification

6️⃣ Discussion

# 4️⃣ Algorithme d'identification d'adresses

{{< include sections/4-algo-identif.qmd >}}

# Plan de la présentation

1️⃣ Contexte

2️⃣ Utilisation du référentiel Gaïa

3️⃣ Moteur de recherche ElasticSearch

4️⃣ Algorithme d'identification d'adresses

**5️⃣ Performances de l'algorithme d'identification**

6️⃣ Discussion

# 5️⃣ Performances de l'algorithme d'identification

{{< include sections/5-results.qmd >}}

# Plan de la présentation

1️⃣ Contexte

2️⃣ Utilisation du référentiel Gaïa

3️⃣ Moteur de recherche ElasticSearch

4️⃣ Algorithme d'identification d'adresses

5️⃣ Performances de l'algorithme d'identification

**6️⃣ Discussion**

# 6️⃣ Discussion

{{< include sections/6-discussion.qmd >}}

# Bibliographie

1. Chaudhuri, S., et al. (2003). *Robust and efficient fuzzy match for online data cleaning*. [lien](https://courses.cs.washington.edu/courses/cse591d/03sp/chaudhuri.pdf).  
   
2. Kathare, N., et al. (2022). *A Comprehensive Study of Elastic Search*. *Journal of Research in Science and Engineering*, 4(11). [lien](https://doi.org/10.53469/jrse.2022.04(11).07).  

3. Wikipedia. (n.d.). *Elasticsearch*. [lien](https://fr.wikipedia.org/wiki/Elasticsearch).  

# Merci au SSPlab : Julien Pramil, Lino Galiana, Olivier Meslin, Marie-Pierre Joubert et Tom Seimandi
# Merci à Heidi Koumarianos
# Et enfin, merci pour votre attention !